# Generated by Django 6.0 on 2026-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('icon', models.ImageField(upload_to='icon/', verbose_name='Иконка сайта')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
